from .secante import secante
from .regla_falsa import regla_falsa
from .raices_multiples import raices_multiples
from .sor import sor
from .punto_fijo import punto_fijo
from .newton import newton
from .metodo_grafico import metodo_grafico
from .jacobi import jacobi
from .gauss_seidel import gauss_seidel
from .biseccion import biseccion
from .lagrange import lagrange
from .newtonint import newtonint
from .vandermonde import vandermonde
from .spline_lineal import spline_lineal
from .spline_cubico import spline_cubico